//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace karbantartasSzerver.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Karbantarto01_DBEntities : DbContext
    {
        public Karbantarto01_DBEntities()
            : base("name=Karbantarto01_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assets> assets { get; set; }
        public virtual DbSet<mainCategory> mainCategory { get; set; }
        public virtual DbSet<occupations> occupations { get; set; }
        public virtual DbSet<operations> operations { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<subCategory> subCategory { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
