//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace karbantartasSzerver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mainCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mainCategory()
        {
            this.subCategory = new HashSet<subCategory>();
        }
    
        public int id { get; set; }
        public string mainCategoryName { get; set; }
        public int mainCategoryWorkMinutes { get; set; }
        public int mainCategoryOccupation { get; set; }
        public Nullable<int> mainCategoryOpId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subCategory> subCategory { get; set; }
        public virtual occupations occupations { get; set; }
    }
}
