//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace karbantartasSzerver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class operations
    {
        public int id { get; set; }
        public int opId { get; set; }
        public string opName { get; set; }
        public int opWorkMinutes { get; set; }
    }
}
