//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace karbantartasSzerver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subCategory
    {
        public int id { get; set; }
        public string subCategoryName { get; set; }
        public int subCategoryLevel { get; set; }
        public int subMainId { get; set; }
        public Nullable<int> subCategoryWorkMinutes { get; set; }
        public int subCategoryOccupation { get; set; }
        public Nullable<int> subCategoryOpId { get; set; }
    
        public virtual mainCategory mainCategory { get; set; }
        public virtual occupations occupations { get; set; }
    }
}
