//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace karbantartasSzerver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string username { get; set; }
        public string fullName { get; set; }
        public int roleId { get; set; }
        public Nullable<int> occupationId { get; set; }
        public string token { get; set; }
        public string password { get; set; }
    
        public virtual occupations occupations { get; set; }
    }
}
